spring.application.name=user.service

spring.config.import=optional:file:./.env[.properties]

spring.jpa.hibernate.ddl-auto=validate
spring.data.redis.url=${REDIS_URL}

jwt.secret=${SECRET}
jwt.issuer=${ISSUER}
jwt.audience=${AUDIENCE}

debug=true
