spring.application.name=user.service

spring.config.import=optional:file:./.env[.properties]

spring.jpa.hibernate.ddl-auto=validate
spring.data.redis.url=${REDIS_URL}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=${SECRET}
jwt.issuer=${ISSUER}
jwt.audience=${AUDIENCE}

debug=true
